### ISSUE TITLE
Doesnt work on usage according to documentation

### ISSUE THREAD

**Issue by suprithwork** [imudin/vue-vr#2]
Hi , I have done an npm install and used the component as explained. But the images dont render in pano or cube pano or any other. Its just blank. I have no errors also. Do i need to install any dependencies??

I also cloned the repository and tried. There is a memory crash because of the rendering of the connection scenes. Can you please help me making this work.

**Comment by suprithwork** [comment]
I have rechecked and changed few things in my code. Now it works. But when I put the Pano component in div it fails to work. Do you know why this scenario occurs so that I can find a fix??

**Comment by imudin** [comment]
There is memory issue when you clone the repo and run locally. I will fix it later.
But there is no this issue if you use it as library. 
as for next issue, could you plz share some demo in jsfiddle or other? it would be good if u ask in stackoverflow unless it is bug report

**Comment by imudin** [comment]
Closing not active issue
