### ISSUE TITLE
Can i use multiple <Pano> with OwlCarousel?

### ISSUE THREAD

**Issue by samirortiz** [imudin/vue-vr#5]
I trying to implement a carousel with multiple vr images. Is that possible?
I try this:

<template>
    <carousel :nav="true" :center="false" :loop="false" :autoHeight="false" :items="1">
        <div class="slide-step">
            <Pano source="http://10.32.2.131:9090/img/taj-mahal.jpg"></Pano>
        </div>
        <div class="slide-step">
            <Pano source="http://10.32.2.131:9090/img/barcelos.jpg"></Pano>
        </div>
    </carousel> 
</template>

<script>
    import carousel from 'vue-owl-carousel'
    import { Pano } from 'vuejs-vr'
    export default {
      props: ['foto'],
      components: { carousel, Pano },
      mounted(){

      }
    }
</script>

**Comment by imudin** [comment]
@samirortiz  it should work with multiple images or components too. 
Can you share demo in jsfiddle or other?

**Comment by imudin** [comment]
Closing not active issue

**Comment by samirortiz** [comment]
Yeah, it works, sorry about the delay. But there is a problem: the images are in eagger loading, so the browser crashes because there is to many images loading. Can you give me some aproach to lazy load the images into several Pano's?
